disable docs

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -30,20 +30,20 @@ jobs:
         pydocstyle src
         flake8 src tests setup.py
         pylint src
-    - name: Build docs
-      # treat warnings as errors (-W)...
-      # ...but not when being nitpicky (-n)
-      run: |
-          sphinx-build -M html docs/source docs/build -qW
-          sphinx-build -M html docs/source docs/build -Eqn -b coverage
-          if [[ -s docs/build/html/python.txt ]]
-          then
-              echo
-              echo \"Error: Documentation missing:\"
-              echo
-              cat docs/build/html/python.txt
-              exit 1
-          fi
+#    - name: Build docs
+#      # treat warnings as errors (-W)...
+#      # ...but not when being nitpicky (-n)
+#      run: |
+#          sphinx-build -M html docs/source docs/build -qW
+#          sphinx-build -M html docs/source docs/build -Eqn -b coverage
+#          if [[ -s docs/build/html/python.txt ]]
+#          then
+#              echo
+#              echo \"Error: Documentation missing:\"
+#              echo
+#              cat docs/build/html/python.txt
+#              exit 1
+#          fi
 
   build:
     needs: linting-and-docs
